export enum ColorType {
    name = 'name',
    position = 'position',
    bodyText = 'bodyText',
    icon = 'icon',
    background = 'background',
    wrapperBorder = 'wrapperBorder',
    sectionName = 'sectionName',
    cardBackground = 'cardBackground',
    cardTitle = 'cardTitle',
    cardSubtitle = 'cardSubtitle',
    cardCaption = 'cardCaption',
    cardContent = 'cardContent',
    tableBackground = 'tableBackground',
    tableMenuBackground = 'tableMenuBackground',
    tableMenuTitle = 'tableMenuTitle',
    tableMenuSubtitle = 'tableMenuSubtitle',
    tableMenuDescription = 'tableMenuDescription',
    tableMenuBorder = 'tableMenuBorder',
    tableContentBackground = 'tableContentBackground',
    tableContentText = 'tableContentText',
};

export enum Sizing {
    XXS = '2px',
    XS = '4px',
    S = '8px',
    M = '12px',
    L = '16px',
    XL = '32px',
    XXL = '48px',
};
