// <auto-generated />
namespace FinalProject_ADONET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ThirdMigration_UpdateClassAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThirdMigration_UpdateClassAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202105161529421_ThirdMigration_UpdateClassAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}