namespace OpenHarmony.NDK.Bindings.IPC_Kit;

public enum OH_IPC_ErrorCode
{
    OH_IPC_SUCCESS = 0,

    OH_IPC_ERROR_CODE_BASE = 1901000,

    OH_IPC_CHECK_PARAM_ERROR = OH_IPC_ERROR_CODE_BASE,

    OH_IPC_PARCEL_WRITE_ERROR = OH_IPC_ERROR_CODE_BASE + 1,

    OH_IPC_PARCEL_READ_ERROR = OH_IPC_ERROR_CODE_BASE + 2,

    OH_IPC_MEM_ALLOCATOR_ERROR = OH_IPC_ERROR_CODE_BASE + 3,

    OH_IPC_CODE_OUT_OF_RANGE = OH_IPC_ERROR_CODE_BASE + 4,

    OH_IPC_DEAD_REMOTE_OBJECT = OH_IPC_ERROR_CODE_BASE + 5,

    OH_IPC_INVALID_USER_ERROR_CODE = OH_IPC_ERROR_CODE_BASE + 6,

    OH_IPC_INNER_ERROR = OH_IPC_ERROR_CODE_BASE + 7,

    OH_IPC_ERROR_CODE_MAX = OH_IPC_ERROR_CODE_BASE + 1000,

    OH_IPC_USER_ERROR_CODE_MIN = 1909000,

    OH_IPC_USER_ERROR_CODE_MAX = 1909999
}