import { Option } from "@/components/ui/multiple-selector";

export const INTEREST_OPTIONS: Option[] = [
	{ label: "Computer Programming", value: "computer-programming" },
	{ label: "Mathematics", value: "mathematics" },
	{ label: "Physics", value: "physics" },
	{ label: "Chemistry", value: "chemistry" },
	{ label: "Biology", value: "biology" },
	{ label: "Robotics", value: "robotics" },
	{ label: "Artificial Intelligence", value: "artificial-intelligence" },
	{ label: "Data Science", value: "data-science" },
	{ label: "Web Development", value: "web-development" },
	{ label: "Mobile App Development", value: "mobile-app-development" },
	{ label: "Graphic Design", value: "graphic-design" },
	{ label: "Digital Art", value: "digital-art" },
	{ label: "Creative Writing", value: "creative-writing" },
	{ label: "Literature Analysis", value: "literature-analysis" },
	{ label: "History", value: "history" },
	{ label: "Archaeology", value: "archaeology" },
	{ label: "Psychology", value: "psychology" },
	{ label: "Sociology", value: "sociology" },
	{ label: "Economics", value: "economics" },
	{ label: "Political Science", value: "political-science" },
	{ label: "Philosophy", value: "philosophy" },
	{ label: "Astronomy", value: "astronomy" },
	{ label: "Space Exploration", value: "space-exploration" },
	{ label: "Environmental Science", value: "environmental-science" },
	{ label: "Sustainability Studies", value: "sustainability-studies" },
	{ label: "Geology", value: "geology" },
	{ label: "Oceanography", value: "oceanography" },
	{ label: "Engineering", value: "engineering" },
	{ label: "Mechanical Design", value: "mechanical-design" },
	{ label: "Electrical Circuits", value: "electrical-circuits" },
	{ label: "Cybersecurity", value: "cybersecurity" },
	{ label: "Ethical Hacking", value: "ethical-hacking" },
	{ label: "Game Development", value: "game-development" },
	{ label: "Animation", value: "animation" },
	{ label: "3D Modeling", value: "3d-modeling" },
	{ label: "Virtual Reality", value: "virtual-reality" },
	{ label: "Augmented Reality", value: "augmented-reality" },
	{ label: "Machine Learning", value: "machine-learning" },
	{ label: "Quantum Physics", value: "quantum-physics" },
	{ label: "Statistics", value: "statistics" },
	{ label: "Public Speaking", value: "public-speaking" },
	{ label: "Debate", value: "debate" },
	{ label: "Foreign Languages", value: "foreign-languages" },
	{ label: "Linguistics", value: "linguistics" },
	{ label: "Cultural Studies", value: "cultural-studies" },
	{ label: "Anthropology", value: "anthropology" },
	{ label: "Music Theory", value: "music-theory" },
	{ label: "Instrument Playing", value: "instrument-playing" },
	{ label: "Video Production", value: "video-production" },
	{ label: "Photography Techniques", value: "photography-techniques" },
	{ label: "Biotechnology", value: "biotechnology" },
	{ label: "Genetics", value: "genetics" },
	{ label: "Neuroscience", value: "neuroscience" },
	{ label: "Forensic Science", value: "forensic-science" },
	{ label: "Meteorology", value: "meteorology" },
	{ label: "Urban Planning", value: "urban-planning" },
	{ label: "Architecture", value: "architecture" },
	{ label: "Industrial Design", value: "industrial-design" },
	{ label: "Fashion Design", value: "fashion-design" },
	{ label: "Entrepreneurship", value: "entrepreneurship" },
	{ label: "Business Strategy", value: "business-strategy" },
	{ label: "Marketing", value: "marketing" },
	{ label: "Financial Literacy", value: "financial-literacy" },
	{ label: "Cryptocurrency", value: "cryptocurrency" },
	{ label: "Blockchain Technology", value: "blockchain-technology" },
	{ label: "App Design", value: "app-design" },
	{ label: "UI/UX Design", value: "ui-ux-design" },
	{ label: "Competitive Programming", value: "competitive-programming" },
	{ label: "Logic Puzzles", value: "logic-puzzles" },
	{ label: "Math Olympiads", value: "math-olympiads" },
	{ label: "Science Experiments", value: "science-experiments" },
	{ label: "Astronomy Observation", value: "astronomy-observation" },
	{ label: "Botany", value: "botany" },
	{ label: "Zoology", value: "zoology" },
	{ label: "Paleontology", value: "paleontology" },
	{ label: "Ethnobotany", value: "ethnobotany" },
	{ label: "Marine Biology", value: "marine-biology" },
	{ label: "Coding Projects", value: "coding-projects" },
	{ label: "Open Source Contribution", value: "open-source-contribution" },
	{ label: "Debating Policy Issues", value: "debating-policy-issues" },
	{ label: "Journalism", value: "journalism" },
	{ label: "Creative Coding", value: "creative-coding" },
	{ label: "Sound Design", value: "sound-design" },
	{ label: "Theater Production", value: "theater-production" },
	{ label: "Film Studies", value: "film-studies" },
	{ label: "Art History", value: "art-history" },
	{ label: "Calligraphy", value: "calligraphy" },
	{ label: "Sculpting", value: "sculpting" },
	{ label: "Woodworking", value: "woodworking" },
	{ label: "Metalworking", value: "metalworking" },
	{ label: "Pottery", value: "pottery" },
	{ label: "Drawing Techniques", value: "drawing-techniques" },
	{ label: "Digital Illustration", value: "digital-illustration" },
	{ label: "Game Theory", value: "game-theory" },
	{ label: "Logic and Reasoning", value: "logic-and-reasoning" },
	{ label: "Cryptography", value: "cryptography" },
	{ label: "Ethical Philosophy", value: "ethical-philosophy" },
	{ label: "Mythology Studies", value: "mythology-studies" },
	{ label: "Medieval History", value: "medieval-history" },
];