export const roomOptions = [
  {
    id: 1,
    name: "Deluxe King Room",
    originalPrice: 19200,
    currentPrice: 14475,
    discount: 25,
    maxGuests: 2,
    bedType: "1 extra-large double bed",
    size: "21 m²",
    views: ["Garden view", "Pool view", "Inner courtyard view"],
    amenities: [
      "Air conditioning",
      "Private bathroom",
      "Soundproofing",
      "Barbecue",
      "Terrace",
      "Free WiFi",
      "Free toiletries",
      "Bidet",
      "Washing machine",
      "Toilet",
      "Bath or shower",
      "Towels",
      "Linen",
      "Cleaning products",
      "Tile/marble floor",
      "Desk",
      "Seating Area",
      "Private entrance",
    ],
    breakfast: true,
    refundable: false,
    prepayment: true,
    geniusDiscount: true,
    availability: 1,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: 2,
    name: "Premium Ocean View Suite",
    originalPrice: 19893,
    currentPrice: 14919,
    discount: 25,
    maxGuests: 2,
    bedType: "1 king-size bed",
    size: "28 m²",
    views: ["Ocean view", "Pool view"],
    amenities: [
      "Air conditioning",
      "Private bathroom",
      "Soundproofing",
      "Balcony",
      "Terrace",
      "Free WiFi",
      "Free toiletries",
      "Bathtub",
      "Shower",
      "Toilet",
      "Bath or shower",
      "Towels",
      "Linen",
      "Cleaning products",
      "Hardwood floor",
      "Desk",
      "Seating Area",
      "Mini-bar",
      "Coffee machine",
    ],
    breakfast: true,
    refundable: true,
    prepayment: false,
    geniusDiscount: true,
    availability: 3,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: 3,
    name: "Garden Villa",
    originalPrice: 18710,
    currentPrice: 14040,
    discount: 25,
    maxGuests: 4,
    bedType: "1 king-size bed and 2 single beds",
    size: "45 m²",
    views: ["Garden view", "Pool view"],
    amenities: [
      "Air conditioning",
      "2 Private bathrooms",
      "Soundproofing",
      "Private garden",
      "Terrace",
      "Free WiFi",
      "Free toiletries",
      "Bathtub",
      "Shower",
      "Toilet",
      "Bath or shower",
      "Towels",
      "Linen",
      "Cleaning products",
      "Hardwood floor",
      "Desk",
      "Living area",
      "Kitchen",
      "Dining area",
    ],
    breakfast: true,
    refundable: false,
    prepayment: true,
    geniusDiscount: true,
    availability: 2,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: 4,
    name: "Family Suite",
    originalPrice: 19298,
    currentPrice: 14475,
    discount: 25,
    maxGuests: 6,
    bedType: "1 king-size bed and 2 queen-size beds",
    size: "65 m²",
    views: ["Garden view", "Mountain view"],
    amenities: [
      "Air conditioning",
      "2 Private bathrooms",
      "Soundproofing",
      "Balcony",
      "Terrace",
      "Free WiFi",
      "Free toiletries",
      "Bathtub",
      "Shower",
      "Toilet",
      "Bath or shower",
      "Towels",
      "Linen",
      "Cleaning products",
      "Hardwood floor",
      "Desk",
      "Living area",
      "Kitchen",
      "Dining area",
    ],
    breakfast: true,
    refundable: true,
    prepayment: false,
    geniusDiscount: true,
    availability: 4,
    images: ["/placeholder.svg?height=200&width=300"],
  },
];