import { User } from '@/types/user.type';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alice Nguyen',
    email: 'alice.nguyen@example.com',
    bio: 'Frontend developer who loves React and TypeScript.',
    learn: [2, 3],
    teach: [1],
    connections: [2, 3],
    requestConnections: [4],
    sentConnections: [5],
    photoURL: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: '2',
    name: 'Bob Tran',
    email: 'bob.tran@example.com',
    bio: 'Backend enthusiast with a passion for Node.js.',
    learn: [1],
    teach: [2, 3],
    connections: [1],
    requestConnections: [],
    sentConnections: [4, 5],
    photoURL: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: '3',
    name: 'Charlie Le',
    email: 'charlie.le@example.com',
    bio: 'Fullstack developer aiming to improve in DevOps.',
    learn: [4],
    teach: [1, 2],
    connections: [1, 2],
    requestConnections: [],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '4',
    name: 'Diana Pham',
    email: 'diana.pham@example.com',
    bio: 'UI/UX designer diving into coding.',
    learn: [1],
    teach: [2, 3],
    connections: [5],
    requestConnections: [1],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '5',
    name: 'Ethan Vo',
    email: 'ethan.vo@example.com',
    bio: 'QA engineer getting into automation testing.',
    learn: [3],
    teach: [4],
    connections: [4],
    requestConnections: [],
    sentConnections: [1],
    photoURL: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: '6',
    name: 'Fiona Do',
    email: 'fiona.do@example.com',
    bio: 'Tech enthusiast and project manager.',
    learn: [5],
    teach: [2, 3],
    connections: [],
    requestConnections: [],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: '7',
    name: 'George Dang',
    email: 'george.dang@example.com',
    bio: 'Cybersecurity student exploring coding.',
    learn: [1, 2],
    teach: [2, 3],
    connections: [],
    requestConnections: [],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: '8',
    name: 'Hannah Ngo',
    email: 'hannah.ngo@example.com',
    bio: 'Python developer expanding into web development.',
    learn: [1],
    teach: [6],
    connections: [],
    requestConnections: [],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: '9',
    name: 'Ian Bui',
    email: 'ian.bui@example.com',
    bio: 'Blockchain dev sharing his Solidity knowledge.',
    learn: [1, 7],
    teach: [9],
    connections: [],
    requestConnections: [],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: '10',
    name: 'Jasmine Huynh',
    email: 'jasmine.huynh@example.com',
    bio: 'Product designer curious about data science.',
    learn: [8],
    teach: [4],
    connections: [],
    requestConnections: [],
    sentConnections: [],
    photoURL: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
];