/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../React-Native-Learning/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../React-Native-Learning/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../React-Native-Learning/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../React-Native-Learning/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../React-Native-Learning/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../React-Native-Learning/hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../React-Native-Learning/hooks/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../React-Native-Learning/hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../React-Native-Learning/constants/Colors${`?${string}` | `#${string}` | ''}` | `/../React-Native-Learning/hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../React-Native-Learning/hooks/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../React-Native-Learning/hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `/../constants/Colors${`?${string}` | `#${string}` | ''}` | `/../hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `/../hooks/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../React-Native-Learning/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../React-Native-Learning/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../React-Native-Learning/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../React-Native-Learning/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}