default_assignment_data = {
    "name": "TEST FROM API",
    "grading_type": "pass_fail",
    "description": "<p>hgjhgj</p>",
    "published": True,
}


def generate_canvas_assignment_data(
    course_id: int, assignment_group_id: int, secure_params: str
):
    return {
        "assignment": {
            "due_at": None,
            "points_possible": 0,
            "assignment_group_id": str(assignment_group_id),
            "post_to_sis": False,
            "graders_anonymous_to_graders": "0",
            "grader_comments_visible_to_graders": True,
            "grader_names_visible_to_final_grader": True,
            "annotatable_attachment_id": "",
            "secure_params": secure_params,
            "lti_context_id": None,
            "course_id": str(course_id),
            "name": default_assignment_data["name"],
            "submission_types": ["none"],
            "has_submitted_submissions": False,
            "due_date_required": False,
            "max_name_length": 255,
            "allowed_attempts": "-1",
            "in_closed_grading_period": False,
            "graded_submissions_exist": False,
            "omit_from_final_grade": "0",
            "hide_in_gradebook": False,
            "is_quiz_assignment": False,
            "can_duplicate": True,
            "original_course_id": None,
            "original_assignment_id": None,
            "workflow_state": "unpublished",
            "important_dates": False,
            "assignment_overrides": [],
            "publishable": True,
            "hidden": False,
            "unpublishable": True,
            "grading_type": default_assignment_data["grading_type"],
            "submission_type": "none",
            "only_visible_to_overrides": False,
            "anonymous_grading": "0",
            "description": default_assignment_data["description"],
            "grading_standard_id": "",
            "allowed_extensions": None,
            "turnitin_enabled": "0",
            "vericite_enabled": "0",
            "external_tool_tag_attributes": {
                "external_data": "",
                "custom_params": "",
                "line_item": "",
                "link_settings": {"selection_width": "", "selection_height": ""},
                "url": "",
                "content_type": "",
                "content_id": "",
                "new_tab": "0",
            },
            "similarityDetectionTool": "Нет",
            "configuration_tool_type": "",
            "grade_group_students_individually": False,
            "group_category_id": None,
            "peer_reviews": "0",
            "automatic_peer_reviews": "0",
            "peer_review_count": 0,
            "peer_reviews_assign_at": None,
            "intra_group_peer_reviews": "0",
            "anonymous_peer_reviews": "0",
            "notify_of_update": "0",
            "lock_at": None,
            "unlock_at": None,
            "published": default_assignment_data["published"],
        }
    }