// @INFO: Generated file, do not edit directly

export const typographies = {
  'heading-medium-h1': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 64,
    fontSize: '57.33000183105469',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-medium-h2': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 56,
    fontSize: '47.779998779296875',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-medium-h3': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 48,
    fontSize: '39.810001373291016',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-medium-h4': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 40,
    fontSize: '33.18000030517578',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-medium-h5': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 32,
    fontSize: '27.649999618530273',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-medium-h6': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 32,
    fontSize: '23.040000915527344',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-regular-h1': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 64,
    fontSize: '57.33000183105469',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-regular-h2': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 56,
    fontSize: '47.779998779296875',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-regular-h3': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 48,
    fontSize: '39.810001373291016',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-regular-h4': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 40,
    fontSize: '33.18000030517578',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-regular-h5': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 32,
    fontSize: '27.649999618530273',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'heading-regular-h6': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 32,
    fontSize: '23.040000915527344',
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-body-1': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 24,
    fontSize: 17,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-body-2': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 24,
    fontSize: 15,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-caption': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 16,
    fontSize: 13,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-overline': {
    fontFamily: 'Roboto',
    fontWeight: 'Regular',
    lineHeight: 24,
    fontSize: 17,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'uppercase',
    textDecoration: 'none',
  },
  'paragraph-body-1-m': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 24,
    fontSize: 17,
    letterSpacing: '0%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-body-2-m': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 24,
    fontSize: 15,
    letterSpacing: '0%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-caption-m': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 16,
    fontSize: 13,
    letterSpacing: '0%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-overline-m': {
    fontFamily: 'Roboto',
    fontWeight: 'Medium',
    lineHeight: 24,
    fontSize: 17,
    letterSpacing: '0%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'uppercase',
    textDecoration: 'none',
  },
  'paragraph-body-1-i': {
    fontFamily: 'Roboto',
    fontWeight: 'Italic',
    lineHeight: 24,
    fontSize: 17,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-body-2-i': {
    fontFamily: 'Roboto',
    fontWeight: 'Italic',
    lineHeight: 24,
    fontSize: 15,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
  'paragraph-caption-i': {
    fontFamily: 'Roboto',
    fontWeight: 'Italic',
    lineHeight: 16,
    fontSize: 13,
    letterSpacing: '-2%',
    paragraphSpacing: 0,
    paragraphIndent: '0px',
    textCase: 'none',
    textDecoration: 'none',
  },
}

export type MsTypographies = typeof typographies