"""empty message

Revision ID: 78c68d9b395a
Revises: e201a712b7e3
Create Date: 2022-11-16 13:30:48.897362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c68d9b395a'
down_revision = 'e201a712b7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###