export const countries = {
  AFG: { emoji: "🇦🇫", name: "Afghanistan" },
  ALB: { emoji: "🇦🇱", name: "Albania" },
  ALG: { emoji: "🇩🇿", name: "Algeria" },
  AND: { emoji: "🇦🇩", name: "Andorra" },
  AGO: { emoji: "🇦🇴", name: "Angola" },
  ANT: { emoji: "🇦🇬", name: "Antigua & Barbuda" },
  ARG: { emoji: "🇦🇷", name: "Argentina" },
  ARM: { emoji: "🇦🇲", name: "Armenia" },
  ARU: { emoji: "🇦🇼", name: "Aruba" },
  AUS: { emoji: "🇦🇺", name: "Australia" },
  AUT: { emoji: "🇦🇹", name: "Austria" },
  AZE: { emoji: "🇦🇿", name: "Azerbaijan" },
  BAH: { emoji: "🇧🇸", name: "Bahamas" },
  BRN: { emoji: "🇧🇭", name: "Bahrain" },
  BAN: { emoji: "🇧🇩", name: "Bangladesh" },
  BAR: { emoji: "🇧🇧", name: "Barbados" },
  BLR: { emoji: "🏳️", name: "Belarus" },
  BEL: { emoji: "🇧🇪", name: "Belgium" },
  BLZ: { emoji: "🇧🇿", name: "Belize" },
  BEN: { emoji: "🇧🇯", name: "Benin" },
  BER: { emoji: "🇧🇲", name: "Bermuda" },
  BHU: { emoji: "🇧🇹", name: "Bhutan" },
  BOL: { emoji: "🇧🇴", name: "Bolivia" },
  BIH: { emoji: "🇧🇦", name: "Bosnia & Herzegovina" },
  BOT: { emoji: "🇧🇼", name: "Botswana" },
  BRA: { emoji: "🇧🇷", name: "Brazil" },
  IVB: { emoji: "🇻🇬", name: "British Virgin Islands" },
  BRU: { emoji: "🇧🇳", name: "Brunei Darussalam" },
  BUL: { emoji: "🇧🇬", name: "Bulgaria" },
  BUR: { emoji: "🇧🇮", name: "Burundi" },
  BDI: { emoji: "🇧🇮", name: "Burundi" },
  CAM: { emoji: "🇰🇭", name: "Cambodia" },
  CMR: { emoji: "🇨🇲", name: "Cameroon" },
  CAN: { emoji: "🇨🇦", name: "Canada" },
  CPV: { emoji: "🇨🇻", name: "Cape Verde" },
  CAY: { emoji: "🇰🇾", name: "Cayman Islands" },
  CAF: { emoji: "🇨🇫", name: "Central African Republic" },
  TCH: { emoji: "🇹🇩", name: "Chad" },
  CHI: { emoji: "🇨🇱", name: "Chile" },
  CHN: { emoji: "🇨🇳", name: "China" },
  COL: { emoji: "🇨🇴", name: "Colombia" },
  COM: { emoji: "🇰🇲", name: "Comoros" },
  CGO: { emoji: "🇨🇬", name: "Congo" },
  COD: { emoji: "🇨🇩", name: "Congo, Democratic Republic" },
  COK: { emoji: "🇨🇰", name: "Cook Islands" },
  CRC: { emoji: "🇨🇷", name: "Costa Rica" },
  CIV: { emoji: "🇨🇮", name: "Côte d'Ivoire" },
  CRO: { emoji: "🇭🇷", name: "Croatia" },
  CUB: { emoji: "🇨🇺", name: "Cuba" },
  CYP: { emoji: "🇨🇾", name: "Cyprus" },
  CZE: { emoji: "🇨🇿", name: "Czech Republic" },
  DEN: { emoji: "🇩🇰", name: "Denmark" },
  DJI: { emoji: "🇩🇯", name: "Djibouti" },
  DMA: { emoji: "🇩🇲", name: "Dominica" },
  DOM: { emoji: "🇩🇴", name: "Dominican Republic" },
  ECU: { emoji: "🇪🇨", name: "Ecuador" },
  EGY: { emoji: "🇪🇬", name: "Egypt" },
  ESA: { emoji: "🇸🇻", name: "El Salvador" },
  GEQ: { emoji: "🇬🇶", name: "Equatorial Guinea" },
  ERI: { emoji: "🇪🇷", name: "Eritrea" },
  EST: { emoji: "🇪🇪", name: "Estonia" },
  ESW: { emoji: "🇸🇿", name: "Eswatini" },
  ETH: { emoji: "🇪🇹", name: "Ethiopia" },
  FAR: { emoji: "🇫🇴", name: "Faroe Islands" },
  FIJ: { emoji: "🇫🇯", name: "Fiji" },
  FIN: { emoji: "🇫🇮", name: "Finland" },
  FRA: { emoji: "🇫🇷", name: "France" },
  GAB: { emoji: "🇬🇦", name: "Gabon" },
  GAM: { emoji: "🇬🇲", name: "Gambia" },
  GEO: { emoji: "🇬🇪", name: "Georgia" },
  GER: { emoji: "🇩🇪", name: "Germany" },
  GHA: { emoji: "🇬🇭", name: "Ghana" },
  GRE: { emoji: "🇬🇷", name: "Greece" },
  GRN: { emoji: "🇬🇩", name: "Grenada" },
  GUM: { emoji: "🇬🇺", name: "Guam" },
  GUA: { emoji: "🇬🇹", name: "Guatemala" },
  GUI: { emoji: "🇬🇳", name: "Guinea" },
  GBR: { emoji: "🇬🇧", name: "Great Britain" },
  GBS: { emoji: "🇬🇼", name: "Guinea-Bissau" },
  GUY: { emoji: "🇬🇾", name: "Guyana" },
  HAI: { emoji: "🇭🇹", name: "Haiti" },
  HON: { emoji: "🇭🇳", name: "Honduras" },
  HKG: { emoji: "🇭🇰", name: "Hong Kong" },
  HUN: { emoji: "🇭🇺", name: "Hungary" },
  ISL: { emoji: "🇮🇸", name: "Iceland" },
  IND: { emoji: "🇮🇳", name: "India" },
  INA: { emoji: "🇮🇩", name: "Indonesia" },
  IRI: { emoji: "🇮🇷", name: "Iran" },
  IRQ: { emoji: "🇮🇶", name: "Iraq" },
  IRL: { emoji: "🇮🇪", name: "Ireland" },
  ISR: { emoji: "🇮🇱", name: "Israel" },
  ITA: { emoji: "🇮🇹", name: "Italy" },
  JAM: { emoji: "🇯🇲", name: "Jamaica" },
  JPN: { emoji: "🇯🇵", name: "Japan" },
  JOR: { emoji: "🇯🇴", name: "Jordan" },
  KAZ: { emoji: "🇰🇿", name: "Kazakhstan" },
  KEN: { emoji: "🇰🇪", name: "Kenya" },
  PRK: { emoji: "🇰🇵", name: "Korea, Democratic People's Republic" },
  KOR: { emoji: "🇰🇷", name: "Korea, Republic of" },
  KUW: { emoji: "🇰🇼", name: "Kuwait" },
  KGZ: { emoji: "🇰🇬", name: "Kyrgyzstan" },
  LAO: { emoji: "🇱🇦", name: "Laos" },
  LAT: { emoji: "🇱🇻", name: "Latvia" },
  LBN: { emoji: "🇱🇧", name: "Lebanon" },
  LBR: { emoji: "🇱🇷", name: "Liberia" },
  LBA: { emoji: "🇱🇾", name: "Libya" },
  LIE: { emoji: "🇱🇮", name: "Liechtenstein" },
  LTU: { emoji: "🇱🇹", name: "Lithuania" },
  LUX: { emoji: "🇱🇺", name: "Luxembourg" },
  MAC: { emoji: "🇲🇴", name: "Macao" },
  MAD: { emoji: "🇲🇬", name: "Madagascar" },
  MAW: { emoji: "🇲🇼", name: "Malawi" },
  MAS: { emoji: "🇲🇾", name: "Malaysia" },
  MDV: { emoji: "🇲🇻", name: "Maldives" },
  MLI: { emoji: "🇲🇱", name: "Mali" },
  MLT: { emoji: "🇲🇹", name: "Malta" },
  MHL: { emoji: "🇲🇭", name: "Marshall Islands" },
  MTN: { emoji: "🇲🇷", name: "Mauritania" },
  MRI: { emoji: "🇲🇺", name: "Mauritius" },
  MEX: { emoji: "🇲🇽", name: "Mexico" },
  FSM: { emoji: "🇫🇲", name: "Micronesia" },
  MDA: { emoji: "🇲🇩", name: "Moldova" },
  MON: { emoji: "🇲🇨", name: "Monaco" },
  MGL: { emoji: "🇲🇳", name: "Mongolia" },
  MNE: { emoji: "🇲🇪", name: "Montenegro" },
  MAR: { emoji: "🇲🇦", name: "Morocco" },
  MOZ: { emoji: "🇲🇿", name: "Mozambique" },
  MYA: { emoji: "🇲🇲", name: "Myanmar" },
  NAM: { emoji: "🇳🇦", name: "Namibia" },
  NMI: { emoji: "🇲🇵", name: "Northern Mariana Islands" },
  NRU: { emoji: "🇳🇷", name: "Nauru" },
  NEP: { emoji: "🇳🇵", name: "Nepal" },
  NED: { emoji: "🇳🇱", name: "Netherlands" },
  AHO: { emoji: "🇳🇱", name: "Netherlands Antilles" },
  NZL: { emoji: "🇳🇿", name: "New Zealand" },
  NCA: { emoji: "🇳🇮", name: "Nicaragua" },
  NIG: { emoji: "🇳🇪", name: "Niger" },
  NGR: { emoji: "🇳🇬", name: "Nigeria" },
  NIR: { emoji: "🇬🇧", name: "Northern Ireland" },
  MKD: { emoji: "🇲🇰", name: "North Macedonia" },
  NOR: { emoji: "🇳🇴", name: "Norway" },
  OMA: { emoji: "🇴🇲", name: "Oman" },
  PAK: { emoji: "🇵🇰", name: "Pakistan" },
  PLW: { emoji: "🇵🇼", name: "Palau" },
  PLE: { emoji: "🇵🇸", name: "Palestine" },
  PAN: { emoji: "🇵🇦", name: "Panama" },
  PNG: { emoji: "🇵🇬", name: "Papua New Guinea" },
  PAR: { emoji: "🇵🇾", name: "Paraguay" },
  PER: { emoji: "🇵🇪", name: "Peru" },
  PHI: { emoji: "🇵🇭", name: "Philippines" },
  POL: { emoji: "🇵🇱", name: "Poland" },
  POR: { emoji: "🇵🇹", name: "Portugal" },
  PUR: { emoji: "🇵🇷", name: "Puerto Rico" },
  QAT: { emoji: "🇶🇦", name: "Qatar" },
  ROU: { emoji: "🇷🇴", name: "Romania" },
  RUS: { emoji: "🏳️", name: "Russia" },
  RWA: { emoji: "🇷🇼", name: "Rwanda" },
  SKN: { emoji: "🇰🇳", name: "Saint Kitts & Nevis" },
  LCA: { emoji: "🇱🇨", name: "Saint Lucia" },
  VIN: { emoji: "🇻🇨", name: "Saint Vincent & the Grenadines" },
  SAM: { emoji: "🇼🇸", name: "Samoa" },
  SMR: { emoji: "🇸🇲", name: "San Marino" },
  STP: { emoji: "🇸🇹", name: "São Tomé & Príncipe" },
  KSA: { emoji: "🇸🇦", name: "Saudi Arabia" },
  SEN: { emoji: "🇸🇳", name: "Senegal" },
  SRB: { emoji: "🇷🇸", name: "Serbia" },
  SEY: { emoji: "🇸🇨", name: "Seychelles" },
  SLE: { emoji: "🇸🇱", name: "Sierra Leone" },
  SIN: { emoji: "🇸🇬", name: "Singapore" },
  SVK: { emoji: "🇸🇰", name: "Slovakia" },
  SLO: { emoji: "🇸🇮", name: "Slovenia" },
  SOL: { emoji: "🇸🇧", name: "Solomon Islands" },
  SOM: { emoji: "🇸🇴", name: "Somalia" },
  RSA: { emoji: "🇿🇦", name: "South Africa" },
  SSD: { emoji: "🇸🇸", name: "South Sudan" },
  ESP: { emoji: "🇪🇸", name: "Spain" },
  SRI: { emoji: "🇱🇰", name: "Sri Lanka" },
  SDN: { emoji: "🇸🇩", name: "Sudan" },
  SUR: { emoji: "🇸🇷", name: "Suriname" },
  SWE: { emoji: "🇸🇪", name: "Sweden" },
  SUI: { emoji: "🇨🇭", name: "Switzerland" },
  SYR: { emoji: "🇸🇾", name: "Syria" },
  TPE: { emoji: "🇹🇼", name: "Taiwan" },
  TJK: { emoji: "🇹🇯", name: "Tajikistan" },
  TAN: { emoji: "🇹🇿", name: "Tanzania" },
  THA: { emoji: "🇹🇭", name: "Thailand" },
  TLS: { emoji: "🇹🇱", name: "Timor-Leste" },
  TOG: { emoji: "🇹🇬", name: "Togo" },
  TGA: { emoji: "🇹🇴", name: "Tonga" },
  TTO: { emoji: "🇹🇹", name: "Trinidad & Tobago" },
  TUN: { emoji: "🇹🇳", name: "Tunisia" },
  TUR: { emoji: "🇹🇷", name: "Turkey" },
  TKM: { emoji: "🇹🇲", name: "Turkmenistan" },
  TCA: { emoji: "🇹🇨", name: "Turks & Caicos Islands" },
  TUV: { emoji: "🇹🇻", name: "Tuvalu" },
  TWN: { emoji: "🇹🇼", name: "Taiwan" },
  UGA: { emoji: "🇺🇬", name: "Uganda" },
  UKR: { emoji: "🇺🇦", name: "Ukraine" },
  UAE: { emoji: "🇦🇪", name: "United Arab Emirates" },
  USA: { emoji: "🇺🇸", name: "United States" },
  URU: { emoji: "🇺🇾", name: "Uruguay" },
  UZB: { emoji: "🇺🇿", name: "Uzbekistan" },
  VAN: { emoji: "🇻🇺", name: "Vanuatu" },
  VEN: { emoji: "🇻🇪", name: "Venezuela" },
  VIE: { emoji: "🇻🇳", name: "Vietnam" },
  ISV: { emoji: "🇻🇮", name: "Virgin Islands, US" },
  YEM: { emoji: "🇾🇪", name: "Yemen" },
  ZAM: { emoji: "🇿🇲", name: "Zambia" },
  ZIM: { emoji: "🇿🇼", name: "Zimbabwe" },
};