export const dummyPembangunan = [
    {
        id: 1,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Diterima DPRD",
        date: "12 Juli 2021",
        description: "Pembangunan",
        rtrw: "001/001",
        village: "Cilame",
        district: "Tanjung",
        process: "Proses",
        author: "Agus",
        gender: "Laki-laki",
        pdf: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",

        
    },
    {
        id: 2,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 1",
        date: "1 Januari 2023",
        title: "Judul 1",
        description: "Bapak Agus melaporkan bahwa jalan di Desa Cilame rusak parah dan meminta bantuan untuk memperbaikinya, karena jalan tersebut merupakan akses utama warga Desa Cilame.",
        rtrw: "001/001",
        village: "Desa 1",
        district: "Kecamatan 1",
        process: "Proses 1",
        author: "Amanda",
        gender: "Laki-laki",
        pdf: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    },
    {
        id: 3,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 2",
        date: "2 Februari 2023",
        title: "Judul 2",
        description: "Deskripsi 2",
        rtrw: "001/001",
        village: "Desa 2",
        district: "Kecamatan 2",
        process: "Proses 2",
        author: "Agus",
        gender: "Laki-laki",
        pdf: null,
    },
    {
        id: 4,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 3",
        date: "3 Maret 2023",
        title: "Judul 3",
        description: "Deskripsi 3",
        rtrw: "001/001",
        village: "Desa 3",
        district: "Kecamatan 3",
        process: "Proses 3",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 5,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 4",
        date: "4 April 2023",
        title: "Judul 4",
        description: "Deskripsi 4",
        rtrw: "001/001",
        village: "Desa 4",
        district: "Kecamatan 4",
        process: "Proses 4",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 6,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 5",
        date: "5 Mei 2023",
        title: "Judul 5",
        description: "Deskripsi 5",
        rtrw: "001/001",
        village: "Desa 5",
        district: "Kecamatan 5",
        process: "Proses 5",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 7,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 6",
        date: "6 Juni 2023",
        title: "Judul 6",
        description: "Deskripsi 6",
        rtrw: "001/001",
        village: "Desa 6",
        district: "Kecamatan 6",
        process: "Proses 6",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 8,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 7",
        date: "7 Juli 2023",
        title: "Judul 7",
        description: "Deskripsi 7",
        rtrw: "001/001",
        village: "Desa 7",
        district: "Kecamatan 7",
        process: "Proses 7",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 9,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 8",
        date: "8 Agustus 2023",
        title: "Judul 8",
        description: "Deskripsi 8",
        rtrw: "001/001",
        village: "Desa 8",
        district: "Kecamatan 8",
        process: "Proses 8",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 10,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 9",
        date: "9 September 2023",
        title: "Judul 9",
        description: "Deskripsi 9",
        rtrw: "001/001",
        village: "Desa 9",
        district: "Kecamatan 9",
        process: "Proses 9",
        author: "Agus",
        gender: "Laki-laki",
    },
    {
        id: 11,
        image: "https://akcdn.detik.net.id/visual/2020/07/15/ilustrasi-jalan-rusak-cnbc-indonesiamuhammad-sabki-1_169.jpeg?w=715&q=90",
        type: "Pembangunan",
        status: "Status 10",
        date: "10 Oktober 2023",
        title: "Judul 10",
        description: "Deskripsi 10",
        rtrw: "001/001",
        village: "Desa 10",
        district: "Kecamatan 10",
        process: "Proses 10",
        author: "Agus",
        gender: "Laki-laki",
    },
];
