export enum ROLES {
  ADMINISTRADOR = "ADMINISTRADOR",
  SUPERVISOR = "SUPERVISOR",
  SUPERVISOR_LOCAL = "SUPERVISOR_LOCAL",
  OBRERO = "OBRERO",
  USUARIO = "USUARIO",
  MULTIMEDIA = "MULTIMEDIA",
}

export enum ROLES_ID {
  ADMINISTRADOR = "1",
  SUPERVISOR = "4",
  SUPERVISOR_LOCAL = "SUPERVISOR_LOCAL",
  OBRERO = "2",
  USUARIO = "USUARIO",
  MULTIMEDIA = "3",
  SUPERVISOR_DE_OBREROS_DE_PUERTO_RICO = "5",
  ADMINISTRADOR_MULTIMEDIA = "6",
  OBRERO_ENCARGADO_DE_UN_PAIS = "7",
}