import { HolidaysGroupProps } from 'src/utils/Dates/nextBusinessDay/index.interface';

/**
 * @description: Fonte - https://date.nager.at/api/v2/PublicHolidays/2022/BR
 */
export const holidays: HolidaysGroupProps[] = [
  {
    year: 2022,
    holidays: [
      {
        date: '2022-01-01',
        localName: 'Confraternização Universal',
        name: "New Year's Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-03-01',
        localName: 'Carnaval',
        name: 'Carnival',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-04-15',
        localName: 'Sexta-feira Santa',
        name: 'Good Friday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-04-17',
        localName: 'Domingo de Páscoa',
        name: 'Easter Sunday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-04-21',
        localName: 'Dia de Tiradentes',
        name: 'Tiradentes',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-05-01',
        localName: 'Dia do Trabalhador',
        name: 'Labour Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-06-16',
        localName: 'Corpus Christi',
        name: 'Corpus Christi',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-07-09',
        localName: 'Revolução Constitucionalista de 1932',
        name: 'Constitutionalist Revolution of 1932',
        countryCode: 'BR',
        fixed: true,
        global: false,
        counties: ['BR-SP'],
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-09-07',
        localName: 'Dia da Independência',
        name: 'Independence Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-10-12',
        localName: 'Nossa Senhora Aparecida',
        name: 'Our Lady of Aparecida',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-11-02',
        localName: 'Dia de Finados',
        name: "All Souls' Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-11-15',
        localName: 'Proclamação da República',
        name: 'Republic Proclamation Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2022-12-25',
        localName: 'Natal',
        name: 'Christmas Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
    ],
  },
  {
    year: 2023,
    holidays: [
      {
        date: '2023-01-01',
        localName: 'Confraternização Universal',
        name: "New Year's Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-02-21',
        localName: 'Carnaval',
        name: 'Carnival',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-04-07',
        localName: 'Sexta-feira Santa',
        name: 'Good Friday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-04-09',
        localName: 'Domingo de Páscoa',
        name: 'Easter Sunday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-04-21',
        localName: 'Dia de Tiradentes',
        name: 'Tiradentes',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-05-01',
        localName: 'Dia do Trabalhador',
        name: 'Labour Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-06-08',
        localName: 'Corpus Christi',
        name: 'Corpus Christi',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-07-09',
        localName: 'Revolução Constitucionalista de 1932',
        name: 'Constitutionalist Revolution of 1932',
        countryCode: 'BR',
        fixed: true,
        global: false,
        counties: ['BR-SP'],
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-09-07',
        localName: 'Dia da Independência',
        name: 'Independence Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-10-12',
        localName: 'Nossa Senhora Aparecida',
        name: 'Our Lady of Aparecida',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-11-02',
        localName: 'Dia de Finados',
        name: "All Souls' Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-11-15',
        localName: 'Proclamação da República',
        name: 'Republic Proclamation Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2023-12-25',
        localName: 'Natal',
        name: 'Christmas Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
    ],
  },
  {
    year: 2024,
    holidays: [
      {
        date: '2024-01-01',
        localName: 'Confraternização Universal',
        name: "New Year's Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-02-13',
        localName: 'Carnaval',
        name: 'Carnival',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-03-29',
        localName: 'Sexta-feira Santa',
        name: 'Good Friday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-03-31',
        localName: 'Domingo de Páscoa',
        name: 'Easter Sunday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-04-21',
        localName: 'Dia de Tiradentes',
        name: 'Tiradentes',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-05-01',
        localName: 'Dia do Trabalhador',
        name: 'Labour Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-05-30',
        localName: 'Corpus Christi',
        name: 'Corpus Christi',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-07-09',
        localName: 'Revolução Constitucionalista de 1932',
        name: 'Constitutionalist Revolution of 1932',
        countryCode: 'BR',
        fixed: true,
        global: false,
        counties: ['BR-SP'],
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-09-07',
        localName: 'Dia da Independência',
        name: 'Independence Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-10-12',
        localName: 'Nossa Senhora Aparecida',
        name: 'Our Lady of Aparecida',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-11-02',
        localName: 'Dia de Finados',
        name: "All Souls' Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-11-15',
        localName: 'Proclamação da República',
        name: 'Republic Proclamation Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2024-12-25',
        localName: 'Natal',
        name: 'Christmas Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
    ],
  },
  {
    year: 2025,
    holidays: [
      {
        date: '2025-01-01',
        localName: 'Confraternização Universal',
        name: "New Year's Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-03-04',
        localName: 'Carnaval',
        name: 'Carnival',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-04-18',
        localName: 'Sexta-feira Santa',
        name: 'Good Friday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-04-20',
        localName: 'Domingo de Páscoa',
        name: 'Easter Sunday',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-04-21',
        localName: 'Dia de Tiradentes',
        name: 'Tiradentes',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-05-01',
        localName: 'Dia do Trabalhador',
        name: 'Labour Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-06-19',
        localName: 'Corpus Christi',
        name: 'Corpus Christi',
        countryCode: 'BR',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-07-09',
        localName: 'Revolução Constitucionalista de 1932',
        name: 'Constitutionalist Revolution of 1932',
        countryCode: 'BR',
        fixed: true,
        global: false,
        counties: ['BR-SP'],
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-09-07',
        localName: 'Dia da Independência',
        name: 'Independence Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-10-12',
        localName: 'Nossa Senhora Aparecida',
        name: 'Our Lady of Aparecida',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-11-02',
        localName: 'Dia de Finados',
        name: "All Souls' Day",
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-11-15',
        localName: 'Proclamação da República',
        name: 'Republic Proclamation Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
      {
        date: '2025-12-25',
        localName: 'Natal',
        name: 'Christmas Day',
        countryCode: 'BR',
        fixed: true,
        global: true,
        counties: null,
        launchYear: null,
        type: 'Public',
      },
    ],
  },
];