export type RecipeOrigin = {
    label: string;

}

export const recipeOrigins: readonly RecipeOrigin[] = [
    { label: 'Asian' },
    { label: 'European' },
    { label: 'Mediterranean' },
    { label: 'Syrian' },
    { label: 'Latin' },
    { label: 'Middle Eastern' },
    { label: 'North American' },
    { label: 'South American' },
    { label: 'Caribbean' },
    { label: 'African' },
    { label: 'Oceanian' },
    { label: 'Nordic' },
    { label: 'Polynesian' },
    { label: 'Indigenous' },
    { label: 'Arabian' },
    { label: 'Pacific Islander' },
    { label: 'Oriental' },
    { label: 'Andorran' },
    { label: 'Emirati' },
    { label: 'Afghan' },
    { label: 'Antiguan' },
    { label: 'Anguillan' },
    { label: 'Albanian' },
    { label: 'Armenian' },
    { label: 'Angolan' },
    { label: 'Antarctican' },
    { label: 'Argentinian' },
    { label: 'American Samoan' },
    { label: 'Austrian' },
    { label: 'Australian' },
    { label: 'Aruban' },
    { label: 'Alandish' },
    { label: 'Azerbaijani' },
    { label: 'Bosnian' },
    { label: 'Barbadian' },
    { label: 'Bangladeshi' },
    { label: 'Belgian' },
    { label: 'Burkinabe' },
    { label: 'Bulgarian' },
    { label: 'Bahraini' },
    { label: 'Burundian' },
    { label: 'Beninese' },
    { label: 'Saint Barthélemy' },
    { label: 'Bermudian' },
    { label: 'Bruneian' },
    { label: 'Bolivian' },
    { label: 'Brazilian' },
    { label: 'Bahamian' },
    { label: 'Bhutanese' },
    { label: 'Bouvet Islander' },
    { label: 'Motswana' },
    { label: 'Belarusian' },
    { label: 'Belizean' },
    { label: 'Canadian' },
    { label: 'Cocos Islander' },
    { label: 'Congolese' },
    { label: 'Swiss' },
    { label: 'Ivorian' },
    { label: 'Cook Islander' },
    { label: 'Chilean' },
    { label: 'Cameroonian' },
    { label: 'Chinese' },
    { label: 'Colombian' },
    { label: 'Costa Rican' },
    { label: 'Cuban' },
    { label: 'Cape Verdean' },
    { label: 'Curaçaoan' },
    { label: 'Christmas Islander' },
    { label: 'Cypriot' },
    { label: 'Czech' },
    { label: 'German' },
    { label: 'Djiboutian' },
    { label: 'Danish' },
    { label: 'Dominican' },
    { label: 'Algerian' },
    { label: 'Ecuadorean' },
    { label: 'Estonian' },
    { label: 'Egyptian' },
    { label: 'Sahrawi' },
    { label: 'Eritrean' },
    { label: 'Spanish' },
    { label: 'Ethiopian' },
    { label: 'Finnish' },
    { label: 'Fijian' },
    { label: 'Falkland Islander' },
    { label: 'Micronesian' },
    { label: 'Faroese' },
    { label: 'French' },
    { label: 'Gabonese' },
    { label: 'British' },
    { label: 'Grenadian' },
    { label: 'Georgian' },
    { label: 'French Guianese' },
    { label: 'Channel Islander' },
    { label: 'Ghanaian' },
    { label: 'Gibraltarian' },
    { label: 'Greenlandic' },
    { label: 'Gambian' },
    { label: 'Guinean' },
    { label: 'Guadeloupean' },
    { label: 'Equatorial Guinean' },
    { label: 'Greek' },
    { label: 'South Georgian' },
    { label: 'Guatemalan' },
    { label: 'Guamanian' },
    { label: 'Guinea-Bissauan' },
    { label: 'Guyanese' },
    { label: 'Hong Konger' },
    { label: 'Heard and McDonald Islander' },
    { label: 'Honduran' },
    { label: 'Croatian' },
    { label: 'Haitian' },
    { label: 'Hungarian' },
    { label: 'Indonesian' },
    { label: 'Irish' },
    { label: 'Israeli' },
    { label: 'Manx' },
    { label: 'Indian' },
    { label: 'Chagosian' },
    { label: 'Iraqi' },
    { label: 'Iranian' },
    { label: 'Icelandic' },
    { label: 'Italian' },
    { label: 'Jersey' },
    { label: 'Jamaican' },
    { label: 'Jordanian' },
    { label: 'Japanese' },
    { label: 'Kenyan' },
    { label: 'Kyrgyzstani' },
    { label: 'Cambodian' },
    { label: 'I-Kiribati' },
    { label: 'Comoran' },
    { label: 'Kittitian' },
    { label: 'North Korean' },
    { label: 'South Korean' },
    { label: 'Kuwaiti' },
    { label: 'Caymanian' },
    { label: 'Kazakhstani' },
    { label: 'Laotian' },
    { label: 'Lebanese' },
    { label: 'Saint Lucian' },
    { label: 'Liechtensteiner' },
    { label: 'Sri Lankan' },
    { label: 'Liberian' },
    { label: 'Mosotho' },
    { label: 'Lithuanian' },
    { label: 'Luxembourger' },
    { label: 'Latvian' },
    { label: 'Libyan' },
    { label: 'Moroccan' },
    { label: 'Monégasque' },
    { label: 'Moldovan' },
    { label: 'Montenegrin' },
    { label: 'Saint Martin Islander' },
    { label: 'Malagasy' },
    { label: 'Marshallese' },
    { label: 'Macedonian' },
    { label: 'Malian' },
    { label: 'Myanmarese' },
    { label: 'Mongolian' },
    { label: 'Macao' },
    { label: 'Northern Mariana Islander' },
    { label: 'Martiniquais' },
    { label: 'Mauritanian' },
    { label: 'Montserratian' },
    { label: 'Maltese' },
    { label: 'Mauritian' },
    { label: 'Maldivian' },
    { label: 'Malawian' },
    { label: 'Mexican' },
    { label: 'Malaysian' },
    { label: 'Mozambican' },
    { label: 'Namibian' },
    { label: 'New Caledonian' },
    { label: 'Nigerien' },
    { label: 'Norfolk Islander' },
    { label: 'Nigerian' },
    { label: 'Nicaraguan' },
    { label: 'Dutch' },
    { label: 'Norwegian' },
    { label: 'Nepali' },
    { label: 'Nauruan' },
    { label: 'Niuean' },
    { label: 'New Zealander' },
    { label: 'Omani' },
    { label: 'Panamanian' },
    { label: 'Peruvian' },
    { label: 'French Polynesian' },
    { label: 'Papua New Guinean' },
    { label: 'Filipino' },
    { label: 'Pakistani' },
    { label: 'Polish' },
    { label: 'Saint Pierrais' },
    { label: 'Pitcairn Islander' },
    { label: 'Puerto Rican' },
    { label: 'Palestinian' },
    { label: 'Portuguese' },
    { label: 'Palauan' },
    { label: 'Paraguayan' },
    { label: 'Qatari' },
    { label: 'Réunionese' },
    { label: 'Romanian' },
    { label: 'Serbian' },
    { label: 'Russian' },
    { label: 'Rwandan' },
    { label: 'Saudi Arabian' },
    { label: 'Solomon Islander' },
    { label: 'Seychellois' },
    { label: 'Sudanese' },
    { label: 'Swedish' },
    { label: 'Singaporean' },
    { label: 'Saint Helenian' },
    { label: 'Slovenian' },
    { label: 'Svalbardian' },
    { label: 'Slovak' },
    { label: 'Sierra Leonean' },
    { label: 'Sammarinese' },
    { label: 'Senegalese' },
    { label: 'Somali' },
    { label: 'Surinamer' },
    { label: 'South Sudanese' },
    { label: 'São Toméan' },
    { label: 'Salvadoran' },
    { label: 'Sint Maartener' },
    { label: 'Swazi' },
    { label: 'Turks and Caicos Islander' },
    { label: 'Chadian' },
    { label: 'French Southern and Antarctic Landian' },
    { label: 'Togolese' },
    { label: 'Thai' },
    { label: 'Tajik' },
    { label: 'Tokelauan' },
    { label: 'Timorese' },
    { label: 'Turkmen' },
    { label: 'Tunisian' },
    { label: 'Tongan' },
    { label: 'Turkish' },
    { label: 'Trinidadian' },
    { label: 'Tuvaluan' },
    { label: 'Taiwanese' },
    { label: 'Tanzanian' },
    { label: 'Ukrainian' },
    { label: 'Ugandan' },
    { label: 'American' },
    { label: 'Uruguayan' },
    { label: 'Uzbekistani' },
    { label: 'Vatican Citizen' },
    { label: 'Saint Vincentian' },
    { label: 'Venezuelan' },
    { label: 'British Virgin Islander' },
    { label: 'US Virgin Islander' },
    { label: 'Vietnamese' },
    { label: 'Ni-Vanuatu' },
    { label: 'Wallisian' },
    { label: 'Samoan' },
    { label: 'Kosovar' },
    { label: 'Yemeni' },
    { label: 'Mahoran' },
    { label: 'South African' },
    { label: 'Zambian' },
    { label: 'Zimbabwean' }
];