export const projects = [
    {
        id: 'bind',
        index: 1,
        name: 'Bind',
        thumbnail: '/projects/bind.png',
        desc: 'A social media platform designed to bring people closer together.',
        shortDesc:
            'A social media platform designed to bring people closer together.',
        year: '24',
        projectLink: 'https://bind-app-demo.vercel.app',
        githubLink: 'https://github.com/BimaPn/bind-server',
    },
    {
        id: 'jitu',
        name: 'Jitu!',
        index: 2,
        thumbnail: '/projects/jitu.png',
        desc: 'A simple system to help schools track and manage student violations.',
        shortDesc:
            'A simple system to help schools track and manage student violations.',
        year: '24',
        projectLink: '#',
        githubLink: 'https://github.com/fabianazh/jitu',
    },
    {
        id: 'tictactest',
        name: 'TicTacTest',
        index: 3,
        thumbnail: '/projects/tictactest.png',
        desc: 'TicTacTest is your go-to destination for a classic game of Tic Tac Toe in its purest form.',
        shortDesc: 'Your go-to destination for a classic game of TicTacToe.',
        year: '23',
        projectLink: 'https://fabianazh.github.io/tic-tac-test',
        githubLink: 'https://github.com/fabianazh/tic-tac-test',
    },
    {
        id: 'zufar-portfolio',
        index: 4,
        name: 'Portfolio Web',
        thumbnail: '/projects/portfolio.png',
        desc: 'A professional web portfolio I designed, featuring a clean and engaging interface.',
        shortDesc:
            'A professional web portfolio I designed, featuring a clean and engaging interface.',
        year: '24',
        projectLink: 'https://zufarms.vercel.app',
        githubLink: 'https://fabianazh.github.io/portfolio-zufar',
    },
    {
        id: 'quranku',
        index: 5,
        name: 'QuranKu',
        thumbnail: '/projects/quranku.png',
        desc: 'A modern and accessible Quran web application designed to provide users with a seamless reading experience anywhere, anytime.',
        shortDesc:
            'A modern and accessible Quran web application designed to provide users with a seamless reading experience anywhere, anytime.',
        year: '23',
        projectLink: 'https://quranku-one.vercel.app',
        githubLink: 'https://github.com/fabianazh/quranku',
    },
    {
        id: 'starbucks-clone',
        index: 6,
        name: 'Starbucks Clone',
        thumbnail: '/projects/starbucks.png',
        desc: 'A landing page from popular coffee shop.',
        shortDesc: 'A landing page from popular coffee shop.',
        year: '23',
        projectLink: 'https://quranku-one.vercel.app',
        githubLink: 'https://github.com/fabianazh/quranku',
    },
]