// const demoText = [
//   'Alice opened the door and found that it led into a small passage, not much larger than a rat-hole: she knelt down and looked along the passage into the loveliest garden you ever saw. How she longed to get out of that dark hall, and wander about among those beds of bright flowers and those cool fountains, but she could not even get her head through the doorway; "and even if my head would go through," thought poor Alice, "it would be of very little use without my shoulders.Oh, how I wish I could shut up like a telescope! I think I could, if I only knew how to begin." For, you see, so many out - of - the - way things had happened lately, that Alice had begun to think that very few things indeed were really impossible.',
//   "Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed; it was labelled “ORANGE MARMALADE”, but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody underneath, so managed to put it into one of the cupboards as she fell past it.",
// ];

const meta = {
  title: "Alice's Adventures in Wonderland",
  author: "Lewis Carroll",
  id: "id_123",
  userId: "user_321",
  version: "0",
};

const body1 = [
  {
    pageIndex: 0,
    pageContent: [
      "1",
      "2",
      "3",
      " ",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      " ",
      "8",
      "9",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "0",
      "a",
      "b",
      "o",
      "u",
      "t",
      " ",
      "b",
      "y",
      "e",
      "TAB",
      "-",
      "c",
      "a",
      "b",
      "o",
      "u",
      "t",
      " ",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      "a",
      "b",
      "o",
      "u",
      "t",
      " ",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      " ",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      "0",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      "a",
      "b",
      "o",
      "u",
      "t",
      "1",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      "2",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      "a",
      "b",
      "o",
      "u",
      "t",
      "3",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
      "4",
      "ENTER",
      "b",
      "y",
      "e",
      "5",
      "-",
      "c",
      "a",
      "b",
      "o",
      "u",
      "t",
      "6",
      "ENTER",
      "b",
      "y",
      "e",
      " ",
      "-",
      "c",
    ],
  },
  { pageIndex: 1, pageContent: ["1", "TAB", "(", "2", ")", "3", "5", " "] },
  { pageIndex: 2, pageContent: ["A", "V", "B"] },
];

const body = [
  {
    pageIndex: 0,
    pageContent: [
      ["a", "b", "c", "TAB", "ENTER"],
      [
        "1",
        "2",
        "3",
        " ",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
      ],
    ],
  },
  {
    pageIndex: 1,
    pageContent: [
      ["1", " ", "3", " ", "ENTER", "a", "b"],
      ["a", "b", "c", "TAB", "ENTER"],
    ],
  },
  {
    pageIndex: 2,
    pageContent: [
      ["Q", "$", "&", "1", "ENTER"],
      ["a", "b", "c", "TAB", "ENTER"],
    ],
  },
];

export const demoBook = { meta, body };