export const BSai: string[] = [
    "ENGL 110",
    "First Year Seminar",
    "Discovering Learning Experience",
    "Multicultural Requirement",
    "3 credits Group A Breadth",
    "3 credits Group B Breadth",
    "3 credits Group C Breadth",
    "3 credits Group D Breadth",
    "9 credits Engineering Breadth",
    "Capstone",
    "Second Writing Requirement",
    "CISC 108",
    "CISC 181",
    "CISC 210",
    "CISC 220",
    "CISC 260",
    "CISC 275",
    "CISC 303",
    "CISC 320",
    "CISC 355",
    "CISC 304",
    "CISC 442",
    "CISC 483",
    "CISC 484",
    "MATH 210",
    "MATH 241",
    "Lab Requirement",
    "Probability/Statistics Course",
    "System Requirement",
    "12 credits Restricted Electives",
    "CISC elective above 300",
    "Total 124 credits"
];