require('colors');
module.exports = [
  '                                                                               '.black + '\n',
  '                                 '.black + 'MMMMMMMMMMMMMM'.yellow + '                                '.black + '\n',
  '                             '.black + 'MMMMMMMMMMMMMMMMMMMMMM'.yellow + '                            '.black + '\n',
  '                        '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                         '.black + '\n',
  '                     '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                     '.black + '\n',
  '                   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                   '.black + '\n',
  '                '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                 '.black + '\n',
  '              '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '               '.black + '\n',
  '            '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '             '.black + '\n',
  '          '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '             '.black + '\n',
  '         '.black + 'MMMMMM'.yellow + '     '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '     '.black + 'MMMMMMMMMMMMMM'.yellow + '           '.black + '\n',
  '        '.black + 'MMMM'.yellow + '           '.black + 'MMMMMMMMMMMMMMMMMMMMMM'.yellow + '             '.black + 'MMMMMMMMMMM'.yellow + '          '.black + '\n',
  '       '.black + 'MMM'.yellow + '     '.black + 'MMMM'.white + '      '.black + 'MMMMMMMMMMMMMMMMMMM'.yellow + '    '.black + 'MMMMMMM'.white + '     '.black + 'MMMMMMMMMM'.yellow + '         '.black + '\n',
  '      '.black + 'MMM'.yellow + '    '.black + 'MMMMM'.white + '        '.black + 'MMMMMMMMMMMMMMMM'.yellow + '    '.black + 'MMMMMMM'.white + '        '.black + 'MMMMMMMMMM'.yellow + '        '.black + '\n',
  '     '.black + 'MMMM'.yellow + '   '.black + 'MMMMM'.white + '          '.black + 'MMMMMMMMMMMMMM'.yellow + '    '.black + 'MMMMMMM'.white + '          '.black + 'MMMMMMMMMM'.yellow + '       '.black + '\n',
  '     '.black + 'MMM'.yellow + '   '.black + 'MMMMM '.white + '           '.black + 'MMMMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMM'.white + '           '.black + 'MMMMMMMMMM'.yellow + '      '.black + '\n',
  '    '.black + 'MMMM'.yellow + '  '.black + 'MMMMMMMM'.white + '          '.black + 'MMMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMM'.white + '          '.black + 'MMMMMMMMMM'.yellow + '      '.black + '\n',
  '    '.black + 'MMM'.yellow + '   '.black + 'MMMMMMMM '.white + '         '.black + 'MMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMM'.white + '          '.black + 'MMMMMMMMMM'.yellow + '     '.black + '\n',
  '   '.black + 'MMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMM '.white + '   '.black + 'MMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMM'.white + '   '.black + 'MMMMMMMMMMM'.yellow + '     '.black + '\n',
  '   '.black + 'MMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMM '.white + '   '.black + 'MMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMM'.white + '   '.black + 'MMMMMMMMMMM'.yellow + '     '.black + '\n',
  '   '.black + 'MMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMM'.white + '   '.black + 'MMMMMMMMMMM'.yellow + '    '.black + 'MMMMMMMMMMMMMMMMM'.white + '   '.black + 'MMMMMMMMMMM'.yellow + '     '.black + '\n',
  '  '.black + 'MMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMM'.white + '    '.black + 'MMMMMMMMMMMM'.yellow + '    '.black + 'MMMMMMMMMMMMMMM'.white + '    '.black + 'MMMMMMMMMMMM'.yellow + '    '.black + '\n',
  '  '.black + 'MMMMMMM'.yellow + '                  '.black + 'MMMMMMMMMMMMMM'.yellow + 'MMMMMMMMMMMMMMMMMMMM '.black + 'MMMMMMMMMMMMM'.yellow + '    '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '    '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '    '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '    '.black + '\n',
  '   '.black + 'MMMMMMM'.yellow + '                                                    '.black + 'MMMMMMMMMMMMM'.yellow + '    '.black + '\n',
  '   '.black + 'MMMMMMM'.yellow + '                                                    '.black + 'MMMMMMMMMMMM'.yellow + '     '.black + '\n',
  '    '.black + 'MMMMMMMM'.yellow + '    '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMMMMM'.yellow + '     '.black + '\n',
  '    '.black + 'MMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMMMMM'.yellow + '     '.black + '\n',
  '    '.black + 'MMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMMMMM'.yellow + '     '.black + '\n',
  '     '.black + 'MMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '  '.black + 'MMMMMMMMMM'.yellow + '      '.black + '\n',
  '     '.black + 'MMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMMM'.yellow + '       '.black + '\n',
  '      '.black + 'MMMMMMMM'.yellow + '    '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMMM'.yellow + '       '.black + '\n',
  '       '.black + 'MMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '  '.black + 'MMMMMMMMM'.yellow + '        '.black + '\n',
  '        '.black + 'MMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMM'.yellow + '         '.black + '\n',
  '         '.black + 'MMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMM'.magenta + ',,,mmmmmmmmm'.magenta + 'MMMMMMMM'.magenta + '   '.black + 'MMMMMMMM'.yellow + '          '.black + '\n',
  '          '.black + 'MMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMM'.magenta + ',MMMMMMMMMMMMMMM'.magenta + 'MMMMM'.magenta + '   '.black + 'MMMMMMMM'.yellow + '           '.black + '\n',
  '           '.black + 'MMMMMMMM'.yellow + '    '.black + 'MMMMMMMMMMM'.magenta + ',MMMMMMMMMMMMMMMMMMM'.magenta + 'M'.magenta + '    '.black + 'MMMMMMM'.yellow + '             '.black + '\n',
  '             '.black + 'MMMMMMM'.yellow + '    '.black + 'MMMMMMMMM'.magenta + ',MMMMMMMMMMMMMMMMMMMM'.magenta + '    '.black + 'MMMMMMMM'.yellow + '             '.black + '\n',
  '               '.black + 'MMMMMMM'.yellow + '    '.black + 'MMMMMM'.magenta + ',MMMMMMMMMMMMMMMMMM'.magenta + '     '.black + 'MMMMMMMM'.yellow + '               '.black + '\n',
  '                '.black + 'MMMMMMMM'.yellow + '    '.black + 'MMM MMMMMMMMMMMMMMMM'.magenta + '      '.black + 'MMMMMMMM'.yellow + '                 '.black + '\n',
  '                  '.black + 'MMMMMMMM'.yellow + '       '.black + 'MMMMMMMMMM'.magenta + '        '.black + 'MMMMMMMMM'.yellow + '                   '.black + '\n',
  '                     '.black + 'MMMMMMMM'.yellow + '                   '.black + 'MMMMMMMMM'.yellow + '                      '.black + '\n',
  '                        '.black + 'MMMMMMMMMMM'.yellow + '      '.black + 'MMMMMMMMMMMMM'.yellow + '                         '.black + '\n',
  '                             '.black + 'MMMMMMMMMMMMMMMMMMMMM'.yellow + '                             '.black + '\n',
  '                                                                               '.black + '\n',
];