// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaContableWeb.Context;

namespace SistemaContableWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201113023052_roles")]
    partial class roles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.AccesoMoneda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IDMonedaAcc")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioModif")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("AccesoMoneda");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.MaestroMoneda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("IdMoneda")
                        .HasColumnType("text");

                    b.Property<bool>("Inactivo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("MaestroMoneda");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.Opciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("GeneraContabilidad_Compra")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GeneraContabilidad_Inventario")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GeneraContabilidad_Nomina")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GeneraContabilidad_Ventas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GenerarComprobantesHistoricos")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("MantenerHistorico_Compra")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MantenerHistorico_Inventario")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MantenerHistorico_Nomina")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MantenerHistorico_Ventas")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioModif")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Opciones");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.PerfilUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Agregar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Editar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Eliminar")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfiles")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Listado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Vista")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("usuarioMofi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PerfilUsuario");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.Perfiles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.acceso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaModif")
                        .HasColumnType("datetime");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("acceso");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("RNC")
                        .HasColumnType("text");

                    b.Property<string>("celular")
                        .HasColumnType("text");

                    b.Property<string>("ciudad")
                        .HasColumnType("text");

                    b.Property<string>("contacto")
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("SistemaContableWeb.Models.Setting.usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.Property<string>("pass")
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}